version: 0.2
phases:
install:
commands:
- pip install awscli # Ensure AWS CLI is available
build:
commands:
- echo "Packaging Lambda function..."
- zip -r lambda_function.zip .
- echo "Updating Lambda function in AWS..."
- aws lambda update-function-code --function-name ImageDetectorLambda --zip-file fileb://lambda_function.zip